---
name: Build Linux (ARM64)
permissions: {}
on:
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.14'

jobs:
  build:
    name: ARM64
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          submodules: recursive

      - name: Install apt deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            g++ \
            libcap-dev \
            libcurl4-openssl-dev \
            libdrm-dev \
            libevdev-dev \
            libgl-dev \
            libglib2.0-dev \
            libmfx-dev \
            libnuma-dev \
            libpulse-dev \
            libssl-dev \
            libva-dev \
            libwayland-dev \
            libx11-dev \
            libxcb-dri3-dev \
            libxcb-present-dev \
            libxfixes-dev \
            libxrandr-dev \
            nlohmann-json3-dev \
            libboost-filesystem-dev \
            libboost-log-dev \
            libminiupnpc-dev \
            libpipewire-0.3-dev \
            libgbm-dev \
            libsystemd-dev \
            libunwind-dev \
            libavcodec-dev \
            libavutil-dev \
            libavformat-dev \
            libswscale-dev \
            libpugixml-dev

      - name: Build
        run: |
          mkdir build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_WERROR=ON \
            -DSUNSHINE_BUILD_HOME=ON \
            -DSUNSHINE_BUILD_TESTS=OFF \
            -DSUNSHINE_EXECUTABLE_NAME=sunshine
          make -j "$(nproc)"
          mkdir -p ../artifacts
          cp sunshine ../artifacts/

      - name: Strip
        run: |
          strip artifacts/sunshine
          ls -lh artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: sunshine-arm64
          path: artifacts/
          if-no-files-found: error
